#import "../../themes/common.typ": *

#separator()

== Scientific meetings organization

#clist("meetings", [Scientific Committee member of the 5#up[th] International Conference on Structural and Physical Aspects of Construction Engineering (SPACE-2022), 12 – 14 October 2022, Kosice, Slovakia #linebreak()
  #link("https://space.uis.svf.tuke.sk/")], [Scientific Committee member of the Civil Engineering Conference, 9 – 10 February 2022, Kosice, Slovakia #linebreak()
  #link("https://cec.svf.tuke.sk/")], [Program Committee member of the “2#up[nd] International Workshop on Advanced Information and Computation Technologies and Systems” (AICTS 2021), December 6 – 10 2021, Irkutsk, Russia #linebreak()
  #link("https://aicts.icc.ru/")], [Program committee member of the “3#up[rd] International Workshop on Information, Computation, and Control Systems for Distributed Environments” (ICCS-DE 2021), July 5 – 9 2021, Irkutsk, Russia #linebreak()
  #link("https://iccs-de.icc.ru/en/")], [Organizing committee member of the “Scientific Solar Summer School” (4Sun), 8 – 12 June 2020, Le Bourget-du-Lac, France #linebreak()
  #link("https://www.univ-smb.fr/solaracademy/2020/02/28/4sun/")

#emph[Organizing committee]: David #sc[Bailleul] (Centre Antoine Favre/USMB), Fanck #sc[Barruel] (PFE/INES), Lamia #sc[Berrah] (LISTIC/USMB), Florence #sc[Besson] (LOCIE/USMB), Denys #sc[Dutykh] (CNRS/LAMA/USMB), Christophe #sc[Ménézo] (LOCIE/USMB), Sébastien #sc[Monnet] (LISTIC/USMB), Aude #sc[Pommeret] (IREGE/USMB), Emilie #sc[Planes] (LEPMI/USMB), Ioannis #sc[Tsanakas] (INES/CEA), Monika #sc[Woloszyn] (LOCIE/USMB), Etienne #sc[Wurtz] (INES/CEA).

#emph[Invited speakers]: Matheus #sc[Bassani] (Universidade Federal do Rio Grande do Sul, Brasil), David #sc[Martineau] (Solaronix, Switzerland), Victoria #sc[Timchenko] (University of New South Wales, Sydney, Australia), Sadok #sc[Bendkhil] (Dracula Technologies, France), Solenn #sc[Berson] (CEA, France), Romain #sc[Cariou] (CEA, France), Louis #sc[De Fontenelle] (Université de Pau et des Pays de l’Adour, France), Philippe #sc[Jacques] (Université Savoie Mont Blanc, France), Laurent #sc[Vuillon] (Université Savoie Mont Blanc, France).], [Member of the organizing committee of the “Second Eurasian Risk-2020 Conference, Symposium and Spring school”, 12 – 19 April 2020, Tbilisi, Georgia #linebreak()
  #link("http://www.eurasianrisk2020.ge/")], [Programme committee member of “the 1st International Workshop on Information, Computation, and Control Systems for Distributed Environments” (ICCS-DE), July 8 – 9 2019, Irkutsk, Russia #linebreak()
  #link("https://iccs-de.icc.ru/ws2019.php")], [Program committee member and co-organizer of the WIN–2014 “#emph[Wave interactions]” workshop, 23–26 April 2014, Linz, Austria (with C.C. #sc[Mei], E. #sc[Pelinovsky], E. #sc[Kartashova] and M. #sc[Onorato])

#emph[List of invited speakers]: Shalva #sc[Amiranashvili], Lushuai #sc[Cao], Amin #sc[Chabchoub], Walter #sc[Craig], Antonio #sc[Degasperis], Ira #sc[Didenkulova], Eric #sc[Falcon], Roger #sc[Grimshaw], Zaher #sc[Hani], Timothée #sc[Jamin], Shijun #sc[Liao], Kiori #sc[Obusé], Miguel #sc[Onorato], Efim #sc[Pelinovsky], Davide #sc[Proment], Stephane #sc[Randoux], Lev #sc[Shemer], Victor #sc[Shrira], Alexey #sc[Slunyaev], Pierre #sc[Suret], Tatiana #sc[Talipova], Elena #sc[Tobisch], Takuji #sc[Waseda]], [Scientific Committee member of the Conference “#emph[Finite Volumes for Complex Applications VII]”, 16 – 20 June 2014, Berlin, Germany #linebreak()
  #link("http://www.wias-berlin.de/fvca7/")], [Member of the Organizing Committee of the Program “#emph[The Mathematics of Oceans]”, May – June 2013, The Fields Institute, Toronto, Canada (along with W. #sc[Craig], D. #sc[Henderson], K. #sc[Lamb], M. #sc[Onorato], E. #sc[Pelinovsky], H. #sc[Segur] and C. #sc[Sulem])

#emph[List of participants:] More than 110 persons. The complete list is available here:
  #link("http://www.fields.utoronto.ca/programs/scientific/12-13/mathofoceans/participants.html")[ http://www.fields.utoronto.ca/programs/scientific/12-13/mathofoceans/participants.html]], [Co-organisation with #link("http://people.bath.ac.uk/pam28/Paul_Milewski,_Professor_of_Mathematics,_University_of_Bath/Milewski.html")[Paul Milewski] (University of Bath) of the Workshop “#emph[Mathematical modeling and analysis of extreme sea waves]” at Fondation des Treilles, France, 8 – 13 October 2012.

#emph[List of invited speakers]: Ricardo #sc[Barros], Oliver #sc[Bühler], Wooyoung #sc[Choi], Didier #sc[Clamond], Frédéric #sc[Dias], Angel #sc[Durán], Denys #sc[Dutykh], Francesco #sc[Fedele], Serge #sc[Guillas], Christian #sc[Kharif], Chiang C. #sc[Mei], Paul #sc[Milewski], Marie #sc[Nguyen], Themistoklis #sc[Stefanakis], Esteban #sc[Tabak], Jon #sc[Wilkening].], [Scientific Committee member of the Conference “#emph[Finite Volumes for Complex Applications VI]”, 6 – 10 June 2011, Prague, Czech Republic #linebreak()
  #link("http://fvca6.fs.cvut.cz/")], [Co-organisation of the #link("http://www.lama.univ-savoie.fr/MathOcean/")[Workshop] #emph[MathOcéan] held at LAMA, University of Savoie, 31 January – 1 February 2011

#emph[List of participants]: Céline #sc[Acary-Robert], Ricardo #sc[Barros], Philippe #sc[Bonneton], Afaf #sc[Bouharguane], Christian #sc[Bourdarias], Didier #sc[Bresch], Mathieu #sc[Cathala], Frderic #sc[Charve], Florent #sc[Chazel], Anne-Laure #sc[Dalibard], Thierry #sc[Dauxois], Laurent #sc[Debreu], Jérémie #sc[Demange], Denys #sc[Dutykh], Mehmet #sc[Ersoy], Stéphane #sc[Gerbi], Marguerite #sc[Gisclon], Boris #sc[Haspot], Christophe #sc[Lacave], David #sc[Lannes], Vincent #sc[Legat], Yong #sc[Lu], Carine #sc[Lucas], Fabien #sc[Marche], Pascal #sc[Noble], Jean #sc[Rajchenbach], Miguel #sc[Rodrigues], Antoine #sc[Rousseau], Chantal #sc[Staquet], Benjamin #sc[Texier], Marion #sc[Tissier], Jean #sc[Zabsonré]], [Co-organisation (with Didier #sc[Bresch] and Marguerite #sc[Gisclon]) of the session entitled “#emph[Numerical models and methods for compressible and two-phase flows]” at the #link("http://www.wpi.ac.at/")[Wolfgang Pauli Institute] (Vienna, Austria), 17 – 21 May 2010 #linebreak()
  #link("http://www.denys-dutykh.com/wpi10/")

#emph[List of invited speakers]: Médéric #sc[Argentina], Marx #sc[Chhay], Catherine #sc[Choquet], Didier #sc[Clamond], Denys #sc[Dutykh], Ahmed Ossama #sc[Ghanem], Marguerite #sc[Gisclon], Theodoros #sc[Katsaounis], Valery #sc[Liapidevskii], Dimitrios #sc[Mitsotakis], Jean #sc[Rajchenbach], Jean-Claude #sc[Saut]], [Co-organisation (with Didier #sc[Bresch] and Céline #sc[Acary-Robert]) of the session entitled “#emph[Numerical methods for complex fluid flows]” at #link("http://www.wpi.ac.at/")[Wolfgang Pauli Institute] (Vienna, Austria), 21 – 25 September 2009 #linebreak()
  #link("http://www.denys-dutykh.com/wpi09/")

#emph[List of invited speakers]: Céline #sc[Acary-Robert], Médéric #sc[Argentina], Marx #sc[Chhay], Didier #sc[Clamond], Vassilios #sc[Dougalis], Denys #sc[Dutykh], Marc #sc[Francius], Marguerite #sc[Gisclon], Theodoros #sc[Katsaounis], Paul #sc[Milewski], Dimitrios #sc[Mitsotakis], Jean-Claude #sc[Saut]], [Atelier Cargèse: “#emph[Modélisation physico–numérique pour les fluides, les particules et le rayonnement. Confrontation modèles physiques et modèles numériques]”. Institut d’Etudes Scientifique de Cargèse, Corsica, France, 24 – 30 September 2006

#emph[List of participants]: Céline #sc[Baranger], Daniel #sc[Bouche], Barbara #sc[Bouffandeau], Jean-Philippe #sc[Braeunig], Michel #sc[Brochard], Christophe #sc[Buet], Gilles #sc[Carre], Frédéric #sc[Chardard], Alain #sc[Decoster], Benoît #sc[Desjardins], Laurent #sc[Desvillettes], Florian #sc[De Vuyst], Frédéric #sc[Dias], Denys #sc[Dutykh], Cédric #sc[Énaux], Christophe #sc[Fochesato], Jean-Michel #sc[Ghidaglia], Laurence #sc[Gozalo], Olivier #sc[Heuzé], Gilles #sc[Kluth], Kim-Claire #sc[Le Thanh], Antoine #sc[Llor], Julien #sc[Mathiaud], Jérôme #sc[Metral], Michaël #sc[Montout], Hai Yen #sc[Nguyen], Frédéric #sc[Pascal], Thierry #sc[Pougeard-Dulimbert], Olivier #sc[Poujade], Agnès #sc[Pujols], Bernard #sc[Rebourcet], Motte #sc[Renaud], Jean-Michel #sc[Rovarch], Gérald #sc[Samba], Muriel #sc[Sesques], Vincent #sc[Siess]])
