#import "../../themes/common.typ": *


== Publications

- My #sc[Erdős] number: #strong[3]
- My $h-$index#footnote[This information is retrieved from Google Scholar server.]: #strong[42]
- My ORCID number: 0000-0001-5247-2788
- Citations statistics: #link("https://scholar.google.com/citations?user=cvOVca4AAAAJ")

=== Preprints under review

#pub-list(category: "Preprints under review", (
  [D. Batic and #me. #emph[Timelike Growth and the Absence of Tempered Fundamental Solutions for a Lorentzian Noncommutative-Geometry-Inspired Wave Operator]. Submitted, 2026],  // Submitted to Lett. Math. Phys., 2026; refereeing pending.
  [S. Mukherjee, L. Bou Nassif, I. Tsanakas, H. Colin, S. Giroux-Julien, H. Pabiou, #me and L. Vuillon. #emph[Physics-Informed Graph Learning for Photovoltaic Power and Module Temperature Modelling]. Submitted, 2026],  // Submitted to EPJ PV (ID pv20260050), 2026.
  [D. Batic and #me. #emph[Spectral and Metric Foundations for Cubic Ghost Quantisation]. Submitted, 2026],  // Submitted to Ann. Henri Poincaré, 2026; refereeing pending.
  [D. Batic and #me. #emph[Global and dynamical viability of the T-duality-inspired Bardeen regular black hole]. Submitted, 2026],  // Submitted to Eur. Phys. J. C (ID EPJC-26-07-009), 2026; refereeing pending.
  [D. Batic and #me. #emph[Spectral Green functions for T-duality-regularised electrostatics in finite and bounded planar geometries]. Submitted, 2026],
  [R. El Cheikh, A. Cheviakov, #me and D. Mitsotakis. #emph[Nonlinear Dynamics of Pulsatile Blood Flow in Viscoelastic Vessels: A Dispersive Wave Approach]. Submitted, 2026],
  [M. Sukaiti, D. Batic and #me. #emph[An exact Kerr-like rotating Morris–Thorne wormhole: throat, ergoregion and equatorial shadow]. Submitted, 2026],  // Submitted to Ann. Phys. (ID 83837), 2026.
  [D. Batic, A. Chrysostomou, A. Cornell and #me. #emph[Quasinormal modes of Schwarzschild de Sitter black holes: spectral branches and the Nariai limit]. Submitted, 2026],
  [D. Batic, A. Chrysostomou, A. Cornell and #me. #emph[Quasinormal modes analysis of a massive scalar field in a Schwarzschild background via the Spectral Method]. Submitted, 2026],
  [D. Batic, #me and M. Sukaiti. #emph[A no-go result for regular GR-connected isotropic Morris–Thorne wormholes in $f(R, T) = R + sigma  R T$ gravity]. Submitted, 2026],  // Rejected by Eur. Phys. J. C (ID EPJC-26-05-359), 2026; transferred to Eur. Phys. J. Plus, still under review.
  [D. Batic, #me. #emph[Spectral Approximation Theory for Quasi-Normal Modes]. Submitted, 2026],
  [D. Batic, #me and J. Faraji. #emph[Spectral Method for Eigenvalue Problems in Quantum Mechanics]. Submitted, 2026],  // Under review at J. Comput. Phys. (ID JCOMP-D-26-01762), 2026.
  [M. Zafar, P. Sabatier, #me, W. Rapuc, R. Paris, A. Piccin, P. Vuillemin and F. Anselmetti. #emph[Human-Enhanced Tsunami Hazard in Large Lakes]. Submitted, 2025],
))

=== Books

#pub-list(category: "Books", (
  [D. Clamond, #me and D. Mitsotakis. #emph[Variational approach to water wave modelling], IAHR WATER MONOGRAPHS, International Association for Hydro-Environment Engineering and Research (IAHR), Spain, 2024. ISBN: 978-90-833476-6-0 #linebreak() #link("https://www.iahr.org/library/infor?pid=29802/")],
  [S. Lespinats, B. Colange and #me. #emph[Nonlinear Dimensionality Reduction Techniques: A Data Structure Preservation Approach], Springer, 2022. ISBN: 978-3-030-81025-2 #linebreak() #link("https://www.springer.com/gp/book/9783030810252/")],
  [G. Khakimzyanov, #me, Z. Fedotova and O. Gusev. #emph[Dispersive Shallow Water Waves: Theory, Modeling, and Numerical Methods], 1#up[st] Ed., Birkhäuser Basel, Springer Nature Switzerland AG, 263 pp., 2020. ISBN: 978-3-030-46266-6 #linebreak() #link("https://www.springer.com/gp/book/9783030462666/")],
  [N. Mendes, M. Chhay, J. Berger and #me. #emph[Numerical methods for diffusion phenomena in building physics: a practical introduction], 2#up[nd] Ed., Springer, Cham, Switzerland, 251 pp., 2020. ISBN: 978-3-030-31573-3 #linebreak() #link("https://www.springer.com/gp/book/9783030315733/")],
  [N. Mendes, M. Chhay, J. Berger and #me. #emph[Numerical methods for diffusion phenomena in building physics], PUCPRESS, Curitiba, Brazil, 224 pp., 2017. ISBN: 978-8-568-32488-2 #linebreak() #link("https://books.google.com/books?id=KNcuDwAAQBAJ")],
))

=== International peer-reviewed journals

#pub-list(category: "International peer-reviewed journals", track-years: true, (
  yd("2026"),
  [D. Batic, #me and M. Sukaiti. #emph[Quasinormal modes of the Kazakov–Solodukhin quantum-corrected black hole: a spectral analysis]. Accepted to #venue[Eur. Phys. J. C], 2026],
  [A. Deeb and #me. #emph[Error estimation for numerical approximations of ODEs via composition techniques. Part I: One-step methods]. Accepted to #venue[Comput. Appl. Math.], 2026 #linebreak() #link("https://arxiv.org/abs/2409.10548/")],
  [S. Mukherjee, L. Vuillon, #me and I. Tsanakas. #emph[Scalable weather data reduction for solar PV analysis using graph-based approach]. Accepted to #venue[Energy Systems], 2026 #linebreak() #link("https://hal.science/hal-05235714/")],
  [D. Batic and #me. #emph[Quasinormal Modes of Gauss–Bonnet Black Holes via the Spectral Method: Scalar, Vector, and Tensor Perturbations]. Accepted to #venue[Phys. Rev. D], 2026],
  [D. Batic, #me and F. Scardigli. #emph[Quasinormal modes of Bonanno–Reuter black holes via the Spectral Method]. #venue[Phys. Rev. D], #strong[114], 024023, 2026 #linebreak() #link("https://doi.org/10.1103/sgt6-kwfl") #linebreak() #link("https://arxiv.org/abs/2607.10199/")],
  [M.K. Andaristiyan, A. Machmudah, R.E. Poetro, W. Hasbi and #me. #emph[Future Subsequent Ballistic Coefficient Estimation Using Deep Learning for Uncontrolled Reentry Object Prediction]. #venue[Acta Astronaut.], #strong[248], 736–749, 2026 #linebreak() #link("https://doi.org/10.1016/j.actaastro.2026.06.022")],
  [A. Rashidi, #me and M. Mokhtari. #emph[Primarily tsunami modeling of the Mw 8.8 Kamchatka Peninsula earthquake on July 29, 2025]. #venue[Nat. Hazards], #strong[122], 450, 2026],
  [D. Batic, C. Boehmer and #me. #emph[Energy conditions in consistent perfect fluid cosmology]. #venue[Ann. Phys.], #strong[491], 170517, 2026 #linebreak() #link("http://arxiv.org/abs/2605.14479/")],
  [D. Batic, #me and M. Sukaiti. #emph[Exact solutions for slowly rotating wormholes in the presence of an anisotropic fluid]. #venue[Class. Quantum Grav.], #strong[43]​(9), 095007, 2026 #linebreak() #link("http://arxiv.org/abs/2605.02555/")],
  [A. Deeb, #me and M. Al Zohbi.  #emph[Error estimation for numerical approximations of ODEs via composition techniques. Part II: Backward difference formulas]. #venue[Comput. Appl. Math.], #strong[45], 355, 2026 #linebreak() #link("http://arxiv.org/abs/2605.06735/")],
  [D. Batic, #me and M. Sukaiti. #emph[Noncommutative geometry-inspired wormholes supported by quasi-de Sitter and Chaplygin-like equations of state]. #venue[Nucl. Phys. B], #strong[1025], 117414, 2026 #linebreak() #link("http://arxiv.org/abs/2603.26257/")],
  [M. Hunt and #me. #emph[Free Surface Waves in Electrohydrodynamics with Prescribed Vorticity Distribution]. #venue[Math. Methods Appl. Sci.], #strong[49]​(7), 7068–7081, 2026],
  [D. Batic, #me and M. Sukaiti. #emph[Exact Spinning Morris–Thorne Wormhole: Causal Structure, Shadows, and Multipole Moments]. #venue[Eur. Phys. J. C], #strong[86], 179, 2026 #linebreak() #link("http://arxiv.org/abs/2602.21906/")],
  [D. Batic, #me and F. Scardigli. #emph[Spectral Analysis of Quasinormal Modes of Planck Stars]. #venue[Eur. Phys. J. C], #strong[86], 165, 2026 #linebreak() #link("http://arxiv.org/abs/2602.19833/")],
  [R. Escobedo, #me, and L. Spector. #emph[Modeling How Hunting Strategies and Pack Size Shape Each Other]. #venue[J. Theor. Biol.], #strong[623], 112390, 2026 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-01182799/")],
  yd("2025"),
  [M. Zafar, #me, R. Paris, R. Gastineau, J. De Sigoyer, E. Duarte, N. Ünsal, N. Harrichhausen, S. Flavard, M. Sahin and P. Sabatier. #emph[Strike-Slip Fault-Generated Paleotsunamis in Lake Iznik (NW Türkiye): Numerical Modeling Corroborated by Coastal Deposits]. #venue[Geophys. Res. Lett.], #strong[52]​(18), e2025GL117422, 2025 #linebreak() #link("https://hal.science/hal-05293993/")],
  [D. Batic, #me, and Z. Babou. #emph[Quasinormal modes of noncommutative geometry-inspired dirty black holes]. #venue[Proc. R. Soc. A], #strong[481]​(2318), 20250021, 2025 #linebreak() #link("https://arxiv.org/abs/2507.19107/")],
  [S. Savvopoulos, A. Al-Aghbari, K. El Kadi, #me and I. Janajreh. #emph[Advancing Freeze Desalination through Ultrasound-Enhanced Modelling: Case Studies and Insights for Commercial Applications]. #venue[Case Stud. Therm. Eng.], #strong[73], 106518, 2025],
  [M. Zafar, P. Sabatier, #me, H. Jomard, W. Rapuc, P. Lajeunesse and E. Chapron. #emph[Modelling earthquake-induced seiche process and subsequent homogenite deposits in lacustrine setting]. #venue[Earth Planet. Sci. Lett.], #strong[660], 119348, 2025],
  [D. Batic, #me and J. Beek. #emph[A Spectral Approach for Quasinormal Frequencies of Noncommutative Geometry-inspired Wormholes]. #venue[Class. Quantum Gravity], #strong[42]​(8), 085003, 2025 #linebreak() #link("https://arxiv.org/abs/2504.02370/")],
  [M. Amazioug, J.-X. Peng, #me and M. Asjad. #emph[Emergence and enhancement of feedback control induced quantum entanglement]. #venue[Eur. Phys. J. Plus], #strong[140], 132, 2025 #linebreak() #link("https://arxiv.org/abs/2311.06578/")],
  [A. Deeb and #me. #emph[Numerical integration of Navier–Stokes equations by time series expansion and stabilized FEM], #venue[Math. Comput. Simul.], #strong[233], 208–236, 2025 #linebreak() #link("https://hal.science/hal-04932473/")],
  [D. Batic and #me. #emph[Instability Analysis of Massive Static Phantom Wormholes via the Spectral Method]. #venue[Eur. Phys. J. C], #strong[85], 144, 2025 #linebreak() #link("https://arxiv.org/abs/2502.05486/")],
  [#me and E. Leichtnam. #emph[On complex algebraic singularities of some genuinely nonlinear PDEs]. #venue[Rend. Mat. Appl.] (7), #strong[46]​(1-2), 63–150, 2025 #linebreak() #link("https://hal.science/hal-03372673/")],
  [#me and Ya. Prykarpatsky. #emph[On integrability of a new dynamical system associated with the BBM-type hydrodynamic flow], #venue[Math. Methods Appl. Sci.], #strong[48]​(1), 107–121, 2025 #linebreak() #link("https://arxiv.org/abs/2407.07900/")],
  yd("2024"),
  [A. Rashidi, M. Mokhtari, #me, M. Masoodi, P. Faridi and S. Kiani. #emph[Researching Tsunami Hazards in Makran: Insights into Challenges and Complex Tsunamis]. #venue[J. Seismol. Earthq. Eng.], #strong[26]​(4), 71–85, 2024],
  [D. Batic, #me and B.L. Giacchini. #emph[A unified spectral approach for quasinormal modes of Lee–Wick black holes], #venue[Phys. Rev. D], #strong[110], 084032, 2024 #linebreak() #link("https://arxiv.org/abs/2410.13245/")],
  [D. Batic and #me. #emph[A Unified Spectral Approach for Quasinormal Modes of Morris–Thorne Wormholes]. #venue[Class. Quantum Gravity], #strong[41]​(21), 215003, 2024 #linebreak() #link("https://arxiv.org/abs/2410.05979/")],
  [P. Djorwé, M. Asjad, Y. Pennec, #me and B. Djafari-Rouhani. #emph[Parametrically enhancing sensor sensitivity at an exceptional point]. #venue[Phys. Rev. Res.], #strong[6], 033284, 2024 #linebreak() #link("https://arxiv.org/abs/2312.05057/")],
  [F. Carbone and #me. #emph[Route to chaos and resonant triads interaction in a truncated Rotating Nonlinear shallow-water model], #venue[PLoS One], #strong[19]​(8), e0305534, 2024 #linebreak() #link("https://hal.science/hal-04670019/")],
  [C. Edet, M. Asjad, #me, N. Ali and O. Abah. #emph[Entropy production rate and correlations of cavity magnomechanical system]. #venue[Phys. Rev. Res.], #strong[6], 033037, 2024 #linebreak() #link("https://arxiv.org/abs/2401.16857/")],
  [A. Deeb and #me. #emph[Stabilized Time Series Expansions for High-Order Finite Element Solutions of Partial Differential Equations]. #venue[Stud. Appl. Math.], #strong[153]​(2), e12708, 2024 #linebreak() #link("https://hal.science/hal-04582473/")],
  [C. Cárdenas-Bravo, #me and S. Lespinats. #emph[On the parameters domain of the single-diode model], #venue[Solar Energy], #strong[277], 112718, 2024 #linebreak() #link("https://hal.science/hal-04622649/")],
  [D. Batic and #me. #emph[Quasinormal Modes in Noncommutative Schwarzschild Black Holes: A Spectral Analysis]. #venue[Eur. Phys. J. C], #strong[84], 622, 2024 #linebreak() #link("https://arxiv.org/abs/2406.03353/")],
  [M. Zafar, #me, P. Sabatier, M. Banjan and J. Kim. #emph[Simulating Sublacustrine Landslide-Induced Paleotsunami in NW Alpine Lake at the Younger Dryas — Early Holocene climatic transition]. #venue[J. Geophys. Res. Solid Earth], #strong[129]​(5), e2023JB028629, 2024 #linebreak() #link("https://hal.science/hal-04592536/")],
  [M. Amazioug, #me, B. Teklu and M. Asjad. #emph[Achieving Strong Magnon Blockade through Magnon Squeezing in a Cavity Magnetomechanical System], #venue[Annalen der Physik], #strong[536]​(4), 2300357, 2024 #linebreak() #link("https://arxiv.org/abs/2308.06367/")],
  [M. Bowen, P. Samozino, M. Vonderscher, #me and B. Morel. #emph[Mathematical modeling of exercise fatigability in the severe domain: A unifying integrative framework in isokinetic condition], #venue[Journal of Theoretical Biology], #strong[578], 111696, 2024 #linebreak() #link("https://hal.science/hal-04330250/")],
  yd("2023"),
  [A. Rashidi, #me and Ch. Beck. #emph[Correction to: Modeling the potential genesis of tsunamis from below an accretionary prism and their potential impact: a case study along the eastern boundary of the Caribbean Plate], #venue[Natural Hazards], #strong[118], 1765, 2023],
  [A. Rashidi, #me and Ch. Beck. #emph[Modeling the potential genesis of tsunamis from below an accretionary prism, and their potential impact: a case study along the eastern boundary of the Caribbean Plate], #venue[Natural Hazards], #strong[118], 307–329, 2023],
  [A. Cheviakov and #me. #emph[Galilei-invariant and energy-preserving extensions of the Benjamin–Bona–Mahony-type equations], #venue[Partial Differ. Equations Appl. Math.], #strong[7], 100519, 2023],
  [M. Cugnet, F. Gallois, A. Kirchev and #me. #emph[NEOLAB: A Scilab tool to simulate the Negative Electrode of Lead-Acid Batteries]. #venue[SoftwareX], #strong[22], 101394, 2023],
  [H. Geoffroy, J. Berger, B. Colange, S. Lespinats and #me. #emph[The use of dimensionality reduction techniques for fault detection and diagnosis in a AHU unit: critical assessment of its reliability], #venue[J. Build. Perform. Simul.], #strong[16]​(3), 249–267, 2023],
  [S. Gasparin, J. Berger, R. Belarbi, #me and N. Mendes. #emph[Solving parametric problems in building renovation with a spectral reduced-order method], #venue[J. Build. Perform. Simul.], #strong[16]​(2), 211–230, 2023],
  yd("2022"),
  [M. Loukili, #me, S. Pincemin, K. Kotrasova and N. Abcha. #emph[Theoretical investigation applied to scattering water wave by rectangular submerged obstacle/and submarine trench]. #venue[Geosciences], #strong[12]​(10), 379, 2022 #linebreak() #link("https://hal.science/hal-03855065/")],
  [A. Machmudah, #me and S. Parman. #emph[Coupled and synchronization models of rhythmic arm movement in planar plane]. #venue[Bioengineering], #strong[9]​(2), 385, 2022],
  [G. Khakimzyanov, Z. Fedotova and #me. #emph[Two-dimensional models of wave hydrodynamics with high accuracy dispersion relation. III. Linear analysis for an uneven bottom]. #venue[Computational Technologies], #strong[27]​(2), 37–53, 2022],
  [B. Colange, L. Vuillon, S. Lespinats and #me. #emph[MING: an interpretative support method for visual exploration of multidimensional data]. #venue[Information Visualization], #strong[21]​(3), 246–269, 2022],
  [D. Blackmore, Ya. Prykarpatsky, M. Prytula, #me and A. Prykarpatsky. #emph[On the integrability of a new generalized Gurevich–Zybin dynamical system, its Hunter–Saxton type reduction and related mysterious symmetries], #venue[Analysis and Mathematical Physics], #strong[12], 66, 2022],
  [#me and J.-L. Verger-Gaugry. #emph[On a class of lacunary almost Newman polynomials modulo $p$ and density theorems], #venue[Uniform Distribution Theory], #strong[17]​(1), 29–54, 2022 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-03517173/")],
  [A. Machmudah, M. Shanmugavel, S. Parman, T.S.B. Abd Manan, #me, S. Beddu and A. Rajabi. #emph[Flight Trajectories Optimization of fixed-wing UAV by Bank-Turn Mechanism], #venue[Drones], #strong[6]​(3), 69, 2022],
  [T. Bueler-Faudree, S. Delamere, #me, A. Rybkin and A. Suleimani. #emph[Fast shallow water-wave solver for plane inclined beaches]. #venue[SoftwareX], #strong[17], 100983, 2022],
  [A. Rashidi, #me, N.K. Farajkhah and L. Audin. #emph[Regional tsunami hazard from splay faults in the Gulf of Oman]. #venue[Ocean Engineering], #strong[243], 110169, 2022],
  yd("2021"),
  [O. Gusev, G. Khakimzyanov, L. Chubarov and #me. #emph[Assessing the frequency dispersion influence on the solitary-wave interaction with a constant sloping beach]. #venue[Journal of Applied Mechanics and Technical Physics], #strong[62], 624–632, 2021],
  [M. Loukili, #me, C. Nadjib and K. Kotrasova. #emph[Analytical and numerical investigations applied to study the reflection and transmission coefficients of wave-rectangular breakwater cited at the bottom of tank]. #venue[Geosciences], #strong[11]​(10), 430, 2021],
  [#me and J.-L. Verger-Gaugry. #emph[Alphabets, rewriting trails and periodic representations in algebraic bases]. #venue[Res. number theory], #strong[7], 64, 2021 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-03090468/")],
  [T.S.B. Abd Manan, S. Beddu, N.L. Mohd Kamal, D. Mohamad, Z. Itam, T. Khan, A. Machmudah, #me, W.H.M. Wan Mohtar, H. Jusoh, F. Mohamed Nazri, M.F.K. Mohd Yapandi, S. Pati, A. Ahmad and N. Wan Rasdi. #emph[Ecological risk indicators for leached heavy metals from coal ash generated at a Malaysian power plant], #venue[Sustainability], #strong[13]​(18), 10222, 2021],
  [G. Khakimzyanov, Z. Fedotova and #me. #emph[Two-dimensional model of wave hydrodynamics with high accuracy dispersion relation. II. Fourth, sixth and eighth orders], #venue[Computational Technologies], #strong[26]​(3), 4–25, 2021],
  [M. Hunt and #me. #emph[Free surface flows in electrohydrodynamics with a constant vorticity distribution], #venue[Water Waves], #strong[3], 297–317, 2021 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-02344438/")],
  [M. Loukili, #me, K. Kotrasova and D. Ning. #emph[Numerical Stability Investigations of the Method of Fundamental Solutions Applied to Wave-Current Interactions Using Generating-Absorbing Boundary Conditions]. #venue[Symmetry], #strong[13]​(7), 1153, 2021],
  [A. Cheviakov, #me and A. Assylbekuly. #emph[On Galilean invariant and energy preserving BBM-type equations]. #venue[Symmetry], #strong[13]​(5), 878, 2021],
  [#me and H. Le Meur. #emph[Derivation of a viscous Serre–Green–Naghdi equation: an impasse?] #venue[Fluids], #strong[6]​(4), 135, 2021 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-02414312/")],
  [M. Loukili, K. Kotrasova and #me. #emph[Numerical modeling of jet at the bottom of tank at moderate Reynolds number using compact Hermitian finite differences method], #venue[Fluids], #strong[6]​(2), 63, 2021],
  [P. Kundu, S.M. Sarkar, A. Rashidi and #me. #emph[Comparison of ground deformation by two infinite faults in different medium], #venue[GEM — Int. J. Geomath.], #strong[12]​(3), 2021],
  yd("2020"),
  [A. Rashidi, #me and Z.H. Shomali. #emph[Horizontal displacements effect in tsunami wave generation in the Western Makran region], #venue[J. Ocean Eng. Mar. Energy], #strong[6], 427–439, 2020],
  [G.S. Khakimzyanov, Z.I. Fedotova and #me. #emph[Two-dimensional model of wave hydrodynamics with high accuracy dispersion relation], #venue[Computational Technologies], #strong[25]​(5), 17–41, 2020],
  [D. Mj (Sarkar) and #me. #emph[Learning extreme wave run-up conditions]. #venue[Applied Ocean Research], #strong[105], 102400, 2020],
  [S.H. Shamsnia and #me. #emph[An analytical study on wave-current-mud interaction], #venue[Water], #strong[12]​(10), 2899, 2020],
  [A. Rashidi, #me, Z.H. Shomali, N.K. Farajkhah and M. Nouri. #emph[A review of tsunami hazard in the Makran subduction zone], #venue[Geosciences], #strong[10]​(9), 372, 2020],
  [A. Abdalazeez, I. Didenkulova, #me and P. Denissenko. #emph[Comparison of dispersive and nondispersive models for modelling long wave run-up on a beach], #venue[Izvestiya], Atmospheric and Oceanic Physics, #strong[56]​(5), 494–501, 2020],
  [G. Sadaka and #me. #emph[Adaptive numerical modelling of tsunami wave generation and propagation with FreeFem++], #venue[Geosciences], #strong[10]​(9), 351, 2020 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-02912526/")],
  [A. Abdalazeez, I.I. Didenkulov, #me and P. Denissenko. #emph[Comparison of Dispersive and Nondispersive Models for Wave Run-Up on a Beach], #venue[Izv. Atmos. Ocean. Phys.], #strong[56], 494–501, 2020],
  [#me and E. Tobisch (Kartashova). #emph[Formation of the dynamic energy cascades in quartic and quintic generalized KdV equations], #venue[Symmetry], #strong[12]​(8), 1254, 2020 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-01070799/")],
  [A. Abdalazeez, I. Didenkulova, D. #strong[Dutykh] and C. Labart. #emph[Extreme inundation statistics on a composite beach], #venue[Water], #strong[12]​(6), 1573, 2020 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-02657270/")],
  [#me and E. Tobisch (Kartashova). #emph[Resonance enhancement by suitably chosen frequency detuning], #venue[Mathematics], #strong[8]​(3), 450, 2020 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-01084796/")],
  [J. Berger, #me, N. Mendes and L. Gosse. #emph[An efficient numerical model for the simulation of coupled heat, air and moisture transfer in porous media], #venue[Engineering Reports], #strong[2]​(2), e12099, 2020 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-02413029/")],
  [J. Berger, T. Busser, T. Colinart and #me. #emph[Critical assessment of a new mathematical model for hysteresis effects on heat and mass transfer in porous building material], #venue[Int. J. Therm. Sci.], #strong[151], 106275, 2020 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-02485497/")],
  [A. Rashidi, Z.H. Shomali, #me and N.K. Farajkhah. #emph[Tsunami hazard assessment in the Makran subduction zone], #venue[Natural Hazards], #strong[100], 861–875, 2020 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-01737767/")],
  [I. Abroug, N. Abcha, #me, A. Jarno and F. Marin. #emph[Experimental and numerical study of the propagation of focused wave groups in the nearshore zone], #venue[Phys. Lett. A], #strong[384]​(6), 126144, 2020 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-02362472/")],
  [J. Berger, S. Gasparin, #me and N. Mendes. #emph[On the comparison of three numerical methods applied to building simulation: finite-differences, RC circuit approximation and a spectral method], #venue[Building Simulation], #strong[13]​(1), 1–18, 2020 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-02140325/")],
  [G. Khakimzyanov and #me. #emph[Long wave interaction with a partially immersed body. Part I: Mathematical models], #venue[Commun. Comput. Phys.], #strong[27]​(2), 321–378, 2020 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-02070055/")],
  [S. Rusconi, #me, A. Zarnescu, D. Sokolovski and E. Akhmatskaya. #emph[An optimal scaling to computationally tractable dimensionless models: Study of latex particles morphology formation], #venue[Comput. Phys. Commun.], #strong[247], 106944, 2020 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-02301950/")],
  yd("2019"),
  [A. Abdalazeez, I. Didenkulova and #me. #emph[Nonlinear deformation and run-up of single tsunami waves of positive polarity: numerical simulations and analytical predictions], #venue[Nat. Hazards Earth Syst. Sci.], #strong[19], 2905–2913, 2019 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-02422302/")],
  [#me. #emph[Numerical simulation of Feller’s diffusion equation], #venue[Mathematics], #strong[7]​(11), 1067, 2019 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-02290284/")],
  [D. Clamond, #me and D. Mitsotakis. #emph[Hamiltonian regularisation of shallow water equations with uneven bottom], #venue[J. Phys. A: Math. Theor.], #strong[52]​(42), 42LT01, 2019 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-02140161/")],
  [J. Berger and #me. #emph[Evaluation of the reliability of building energy performance models for parameter estimation], #venue[Comput. Technologies], #strong[24]​(3), 4–32, 2019 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-02140452/")],
  [M. Abdykarim, J. Berger, #me, L. Soudani and A. Agbossou. #emph[Critical assessment of efficient numerical methods for a long-term simulation of heat and moisture transfer in porous materials], #venue[Int. J. Therm. Sci.], #strong[145], 105982, 2019 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-02162803/")],
  [D. Mitsotakis, Q. Li, E. Peach and #me. #emph[On some model equations for pulsatile flow in viscoelastic vessels], #venue[Wave Motion], #strong[90], 139–151, 2019 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-02135521/")],
  [A. Durán, #me and D. Mitsotakis. #emph[On the multi-symplectic structure of Boussinesq-type systems. II: Geometric discretization], #venue[Phys. D], #strong[397], 1–16, 2019 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-02123559/")],
  [#me and D. Ionescu-Kruse. #emph[Effects of vorticity on the travelling waves of some shallow water two-component systems], #venue[Discrete & Continuous Dynamical Systems — A], #strong[39]​(9), 5521–5541, 2019 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-02094922/")],
  [G. Khakimzyanov, #me, D. Mitsotakis and N. Shokina. #emph[Numerical simulation of conservation laws with moving grid nodes: Application to tsunami wave modelling], #venue[Geosciences], #strong[9]​(5), 197, 2019 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-01223510/")],
  [E. Dinvay, #me and H. Kalisch. #emph[A comparative study of bi-directional Whitham systems], #venue[Appl. Numer. Math.], #strong[141], 248–262, 2019 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-02020212/")],
  [J.-G. Caputo, #me and B. Gleyse. #emph[Coupling conditions for water waves at forks], #venue[Symmetry], #strong[11]​(3), 434, 2019 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-01206504/")],
  [J. Berger, T. Busser, #me and N. Mendes. #emph[An efficient method to estimate sorption isotherm curve coefficients], #venue[ Inv. Prob. Sci. and Eng.], #strong[27]​(6), 735–772, 2019 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-01509113/")],
  [A. Jumabekova, J. Berger, #me, H. Le Meur, A. Foucquier, M. Pailha and Ch. Ménézo. #emph[An efficient numerical model for liquid water uptake in porous material and its parameter estimation], #venue[Numerical Heat Transfer], Part A: Applications, #strong[75]​(2), 110–136, 2019 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-02047087/")],
  [J.-P. Chehab and #me. #emph[On time relaxed schemes and formulations for dispersive wave equations], #venue[AIMS Mathematics], #strong[4]​(2), 254–278, 2019 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-02057433/")],
  [V. Liapidevskii and #me. #emph[On the velocity of turbidity currents over moderate slopes], #venue[Fluid Dyn. Res.], #strong[51], 035501, 2019 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-01719313/")],
  [S. Gasparin, J. Berger, #me and N. Mendes. #emph[An innovative method to determine optimum insulation thickness based on non-uniform adaptive moving grid], #venue[Journal of the Brazilian Society of Mechanical Sciences and Engineering], #strong[41]:173, 2019 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-02045015/")],
  [S. Gasparin, #me and N. Mendes. #emph[A spectral method for solving heat and moisture transfer through consolidated porous media], #venue[Int. J. Numer. Meth. Eng.], #strong[117]​(11), 1143–1170, 2019 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-02023462/")],
  [J. Berger, #me, N. Mendes and B. Rysbaiuly. #emph[A new model for simulating heat, air and moisture transport in porous building materials], #venue[Int. J. Heat Mass Transf.], #strong[134], 1041–1060, 2019 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-02052022/")],
  [S. Gasparin, J. Berger, #me and N. Mendes. #emph[Solving nonlinear diffusive problems in buildings by means of a reduced spectral method], #venue[J. of Build. Perf. Sim.], #strong[12]​(1), 17–36, 2019 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-01513304/")],
  [A. Durán, #me and D. Mitsotakis. #emph[On the multi-symplectic structure of Boussinesq-type systems. I: Derivation and mathematical properties], #venue[Phys. D], #strong[388], 10–21, 2019 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-01930748/")],
  yd("2018"),
  [#me and J.-L. Verger-Gaugry. #emph[On the reducibility and the lenticular sets of zeroes of almost Newman lacunary polynomials], #venue[Arnold Mathematical Journal], #strong[4]​(3-4), 315–344, 2018 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-02045588/")],
  [Y. Pu, R.L. Pego, #me and D. Clamond. #emph[Weakly singular shock profiles for a non-dispersive regularization of shallow-water equations], #venue[Comm. Math. Sci.], #strong[16]​(5), 1361–1378, 2018 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-01794005/")],
  [S. Gasparin, J. Berger, #me and N. Mendes. #emph[An adaptive simulation of nonlinear heat and moisture transfer as a boundary value problem], #venue[Int. J. Therm. Sci.], #strong[133], 120–139, 2018 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-02021293/")],
  [S. Gasparin, J. Berger, #me and N. Mendes. #emph[Advanced reduced-order models for moisture diffusion in porous media], #venue[Transport in Porous Media], #strong[124]​(3), 965–994, 2018 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-01522319/")],
  [A. Rashidi, Z.H. Shomali, #me and N.K. Farajkhah. #emph[Evaluation of tsunami wave energy generated by earthquakes in the Makran subduction zone], #venue[Ocean Eng.], #strong[165]​(1), 131–139, 2018 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-01719939/")],
  [#me, M. Hoefer and D. Mitsotakis. #emph[Solitary wave solutions and their interactions for fully nonlinear water waves with surface tension in the generalized Serre equations]. #venue[Theor. Comp. Fluid Dyn.], #strong[32]​(3), 371–397, 2018 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-01465356/")],
  [J. Berger, H. Le Meur, #me, D. M. Nguyen and A.-C. Grillet. #emph[Analysis and improvement of the VTT mold growth model: application to bamboo fiberboard], #venue[Building and Environment], #strong[138], 262–274, 2018 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-01759837/")],
  [#me and J.-G. Caputo. #emph[Wave dynamics on networks: method and application to the sine–Gordon equation], #venue[Appl. Numer. Math.], #strong[131], 54–71, 2018 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-01160840/")],
  [D. Mitsotakis, #me and Q. Li. #emph[Asymptotic nonlinear and dispersive pulsatile flow in elastic vessels with cylindrical symmetry], #venue[Computers & Mathematics with Applications], #strong[75], 4022–4047, 2018 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-01756720/")],
  [D. Clamond and #me. #emph[Accurate fast computation of steady two-dimensional surface gravity waves in arbitrary depth]. #venue[J. Fluid Mech.], #strong[844], 491–518, 2018 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-01465813/")],
  [J. Berger, S. Gasparin, #me and N. Mendes. #emph[On the solution of coupled heat and moisture transport in porous material], #venue[Transport in Porous Media], #strong[121]​(3), 665–702, 2018 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-01770386/")],
  [S. Gasparin, J. Berger, #me and N. Mendes. #emph[An improved explicit scheme for whole-building hygrothermal simulation], #venue[Building Simulation], #strong[11]​(3), 465–481, 2018 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-01495737/")],
  [V. Liapidevskii, #me and M. Gisclon. #emph[On the modelling of shallow turbidity flows], #venue[Adv. Water Resour.], #strong[113], 310–327, 2018 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-01514095/")],
  [G. Khakimzyanov and #me. #emph[Numerical modelling of surface water wave interaction with a moving wall], #venue[Commun. Comput. Phys.], #strong[23]​(5), 1289–1354, 2018 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-01546833/")],
  [S. Gasparin, J. Berger, #me and N. Mendes. #emph[Stable explicit schemes for simulation of nonlinear moisture transfer in porous materials]. #venue[J. of Build. Perf. Sim.], #strong[11]​(2), 129–144, 2018 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-01404578/")],
  [J. Berger, T. Busser, #me and N. Mendes. #emph[On the estimation of moisture permeability and advection coefficients of a wood fibre material using the optimal experiment design approach], #venue[Experimental Thermal and Fluid Science], #strong[90], 246–259, 2018 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-01498638/")],
  [L. Vuillon, #me and F. Fedele. #emph[Some special solutions to the Hyperbolic NLS equation], #venue[Comm. Nonlinear Sci. Numer. Simulat.], #strong[57], 202–220, 2018 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-00846801/")],
  [G. Khakimzyanov, #me and O. Gusev. #emph[Dispersive shallow water wave modelling. Part IV: Numerical simulation on a globally spherical geometry], #venue[Commun. Comput. Phys.], #strong[23]​(2), 361–407, 2018 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-01558680/")],
  [G. Khakimzyanov, #me and Z. Fedotova. #emph[Dispersive shallow water wave modelling. Part III: Model derivation on a globally spherical geometry], #venue[Commun. Comput. Phys.], #strong[23]​(2), 315–360, 2018 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-01552229/")],
  [G. Khakimzyanov, #me, O. Gusev and N. Shokina. #emph[Dispersive shallow water wave modelling. Part II: Numerical simulation on a globally flat space], #venue[Commun. Comput. Phys.], #strong[23]​(1), 30–92, 2018 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-01551075/")],
  [G. Khakimzyanov, #me, Z. Fedotova and D. Mitsotakis. #emph[Dispersive shallow water wave modelling. Part I: Model derivation on a globally flat space], #venue[Commun. Comput. Phys.], #strong[23]​(1), 1–29, 2018 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-01547833/")],
  [D. Clamond and #me. #emph[Non-dispersive conservative regularisation of nonlinear shallow water and isothermal Euler equations], #venue[Commun. Nonlinear Sci. Numer. Simulat.], #strong[55], 237–247, 2018 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-01509445/")],
  yd("2017"),
  [G. Khakimzyanov and #me. #emph[On supraconvergence phenomenon for second order centered finite differences on non-uniform grids], #venue[J. Comput. Appl. Math.], #strong[326], 1–14, 2017 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-01223522/")],
  [M. Chhay, #me, M. Gisclon and Ch. Ruyer-Quil. #emph[New asymptotic heat transfer model in thin liquid films], #venue[Appl. Math. Model.], #strong[48], 844–859, 2017 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-01224182/")],
  [D. Mitsotakis, #me, A. Assylbekuly and D. Zhakebayev. #emph[On weakly singular and fully nonlinear travelling shallow capillary-gravity waves in the critical regime], #venue[Phys. Lett. A], #strong[381]​(20), 1719–1726, 2017 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-01388481/")],
  [J. Berger, S. Gasparin, #me and N. Mendes. #emph[Accurate numerical simulation of moisture front in porous material], #venue[Building and Environment], #strong[118], 211–224, 2017 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-01419018/")],
  [E. Dinvay, D. Moldabayev, #me and H. Kalisch. #emph[The Whitham equation with surface tension], #venue[Nonlinear Dynamics], #strong[88]​(2), 1125–1138, 2017 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-01504047/")],
  [D. Mitsotakis, #me and J. Carter. #emph[On the nonlinear dynamics of the traveling-wave solutions of the Serre equations], #venue[Wave Motion], #strong[70], 166–182, 2017 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-00984035/")],
  [#me, D. Clamond and M. Chhay. #emph[Serre-type equations in deep water], #venue[Math. Model. Nat. Phenom.], #strong[12]​(1), 23–40, 2017 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-01340379/")],
  [D. Clamond, #me and D. Mitsotakis. #emph[Conservative modified Serre–Green–Naghdi equations with improved dispersion characteristics], #venue[Comm. Nonlinear Sci. Numer. Simul.], #strong[45], 245–257, 2017 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-01232370/")],
  [J. Berger, #me and N. Mendes. #emph[On the optimal experimental design for heat and moisture parameter estimation], #venue[Experimental Thermal and Fluid Science], #strong[81], 109–122, 2017 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-01334414/")],
  yd("2016"),
  [#me and D. Clamond. #emph[Modified Shallow Water Equations for significantly varying seabeds]. #venue[Appl. Math. Modelling], #strong[40]​(23-24), 9767–9787, 2016 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-00675209/")],
  [D. Clamond, #me and A. Galligo. #emph[Algebraic method for constructing singular steady solitary waves: A case study], #venue[Proc. R. Soc. A.], #strong[472]​(2191), 20160194, 2016 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-01290471/")],
  [D. Clamond and #me. #emph[Multi-symplectic structure of fully-nonlinear weakly-dispersive internal gravity waves], #venue[J. Phys. A: Math. Theor.], #strong[49], 31LT01, 2016 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-01296552/")],
  [#me, D. Clamond and A. Durán. #emph[Efficient computation of capillary-gravity generalized solitary waves], #venue[Wave Motion], #strong[65], 1–16, 2016 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-01218989/")],
  [#me and D. Ionescu–Kruse. #emph[Travelling wave solutions for some two-component shallow water models], #venue[J. Diff. Equations], #strong[261]​(2), 1099–1114, 2016 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-01294603/")],
  [#me and O. Goubet. #emph[Derivation of dissipative Boussinesq equations using the Dirichlet-to-Neumann operator approach], #venue[Math. Comput. Simul.], #strong[127], 80–93, 2016 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-00596804/")],
  [F. Carbone, #me and G. El. #emph[Macroscopic dynamics of incoherent soliton ensembles: soliton-gas kinetics and direct numerical modeling: Incoherent soliton ensembles], #venue[EPL], #strong[113], 30003, 2016 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-01248680/")],
  [M. Chhay, #me and D. Clamond. #emph[On the multi-symplectic structure of the Serre–Green–Naghdi equations], #venue[J. Phys. A: Math. Theor.], #strong[49], 03LT01, 2016 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-01221356/")],
  [G. Khakimzyanov, N. Shokina, #me and D. Mitsotakis. #emph[A new run-up algorithm based on local high-order analytic expansions], #venue[J. Comput. Appl. Math.], #strong[298], 82–96, 2016 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-01084811/")],
  yd("2015"),
  [A. Rafiee, #me and F. Dias. #emph[Numerical simulation of wave impact on a rigid wall using a two-phase compressible SPH method]. #venue[Procedia IUTAM], #strong[18], 123–137, 2015 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-00830054/")],
  [D. Clamond, #me and A. Durán. #emph[A plethora of generalised solitary gravity-capillary water waves], #venue[J. Fluid Mech.], #strong[784], 664–680, 2015 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-01081798/")],
  [H. Nersisyan, #me and E. Zuazua. #emph[Generation of 2D water waves by moving bottom disturbances]. #venue[IMA J. Appl. Math.], #strong[80]​(4), 1235–1253, 2015 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-00752364/")],
  [D. Moldabayev, H. Kalisch and #me. #emph[The Whitham equation as a model for surface water waves], #venue[Phys. D], #strong[309], 99–107, 2015 #linebreak() #link("http://hal.univ-savoie.fr/hal-01136855/")],
  [#me, D. Clamond and D. Mitsotakis. #emph[Adaptive modeling of shallow fully nonlinear gravity waves], #venue[RIMS Kôkyûroku], #strong[1947], 45–65, 2015 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-01088440/")],
  [#me, D. Clamond and M. Chhay. #emph[Numerical study of the generalised Klein–Gordon equations], #venue[Phys. D], #strong[304–305], 23–33, 2015 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-00851030/")],
  [#me and E. Tobisch (Kartashova). #emph[Direct dynamical energy cascade in the modified KdV equation], #venue[Phys. D], #strong[297], 76–87, 2015 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-00990724/")],
  [T. Stefanakis, S. Xu, #me and F. Dias. #emph[Run-up amplification of transient long waves]. #venue[Quart. Appl. Math.], LXXIII(1), 177–199, 2015 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-00768597/")],
  yd("2014"),
  [I. S. Gandzha, Yu. V. Sedletsky and #me. #emph[High-order nonlinear Schrödinger equation for the envelope of slowly modulated gravity waves on the surface of finite-depth fluid and its quasi-soliton solutions]. #venue[Ukr. J. Phys.], #strong[59]​(12), 1201–1215, 2014 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-01084747/")],
  [#me and E. Pelinovsky. #emph[Numerical simulation of a solitonic gas in some integrable and non-integrable models], #venue[Phys. Lett. A], #strong[378]​(42), 3102–3110, 2014 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-00913960/")],
  [J.-G. Caputo and #me. #emph[Nonlinear waves in networks: a simple approach using the sine–Gordon equation], #venue[Phys. Rev. E], #strong[90], 022912, 2014 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-00951705/")],
  [D. Mitsotakis, B. Ilan and #me. #emph[On the Galerkin / finite-element method for the Serre equations]. #venue[J. Sci. Comp.], #strong[61]​(1), 166–195, 2014 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-00834064/")],
  [#me and E. Tobisch (Kartashova). #emph[Observation of the Inverse Energy Cascade in the modified Korteweg–de Vries Equation], #venue[Eur. Phys. Lett.], #strong[107], 14001, 2014 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-00991944/")],
  [Z.I. Fedotova, G.S. Khakimzyanov and #me. #emph[Energy equation for certain approximate models of long-wave hydrodynamics], #venue[Russian Journal of Numerical Analysis and Mathematical Modelling], #strong[29]​(3), 167–178, 2014 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-00998927/")],
  [M. Hunt and #me. #emph[Visco-potential flows in electrohydrodynamics], #venue[Phys. Lett. A], #strong[378], 1721–1726, 2014 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-00908724/")],
  [F. Dias, #me, L. O’Brien, E. Renzi and T. Stefanakis. #emph[On the modelling of tsunami generation and tsunami inundation], #venue[Procedia IUTAM], #strong[10], 338–355, 2014 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-00728725/")],
  [C. Viotti, #me and F. Dias. #emph[The conformal-mapping method for surface gravity waves in the presence of variable bathymetry and mean current], #venue[Procedia IUTAM], #strong[11], 110–118, 2014 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-00855780/")],
  [#me. #emph[Evolution of random wave fields in the water of finite depth]. #venue[Procedia IUTAM], #strong[11], 34–43, 2014 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-00864549/")],
  [F. Fedele and #me. #emph[Camassa–Holm equations and vortexons for axisymmetric pipe flows]. #venue[Fluid Dyn. Res.], #strong[46], 015503, 2014 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-00759444/")],
  [#me and D. Clamond. #emph[Efficient computation of steady solitary gravity waves]. #venue[Wave Motion], #strong[51], 86–99, 2014 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-00786077/")],
  yd("2013"),
  [F. Fedele and #me. #emph[Camassa–Holm type equations for axisymmetric Poiseuille pipe flows]. #venue[Procedia IUTAM], #strong[9], 16–24, 2013 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-00752999/")],
  [F. Carbone, #me, J. Dudley and F. Dias. #emph[Extreme wave runup on a vertical cliff]. #venue[Geophys. Res. Lett.], #strong[40]​(12), 3138–3143, 2013 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-00799118/")],
  [A. Durán, #me and D. Mitsotakis. #emph[On the Galilean invariance of some dispersive wave equations], #venue[Stud. Appl. Math.], #strong[131]​(4), 359–388, 2013 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-00664143/")],
  [#me, D. Clamond, P. Milewski and D. Mitsotakis. #emph[Finite volume and pseudo-spectral schemes for the fully nonlinear 1D Serre equations], #venue[European Journal of Applied Mathematics], #strong[24]​(5), 761–787, 2013 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-00587994/")],
  [D. Clamond and #me. #emph[Fast accurate computation of the fully nonlinear solitary surface gravity waves]. #venue[Computers & Fluids], #strong[84], 35–38, 2013 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-00759812/")],
  [C. Viotti, #me, J. Dudley and F. Dias. #emph[Emergence of coherent wave groups in deep-water random sea]. #venue[Phys. Rev. E], #strong[87]​(6), 063001, 2013 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-00795397/")],
  [#me and H. Kalisch. #emph[Boussinesq modeling of surface waves due to underwater landslides], #venue[Nonlin. Processes Geophys.], #strong[20], 267–285, 2013 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-00654386/")],
  [F. Fedele and #me. #emph[Vortexons in axisymmetric Poiseuille pipe flows]. #venue[Eur. Phys. Lett.], #strong[101]​(3), 34003, 2013 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-00756531/")],
  [#me, F. Fedele and M. Chhay. #emph[Geometric numerical schemes for the KdV equation]. #venue[Computational Mathematics and Mathematical Physics], #strong[53]​(2), 221–236, 2013 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-00694896/")],
  [#me, D. Mitsotakis, X. Gardeil and F. Dias. #emph[On the use of finite fault solution for tsunami generation problems]. #venue[Theor. Comput. Fluid Dyn.], #strong[27], 177–199, 2013 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-00509384/")],
  [#me, Th. Katsaounis and D. Mitsotakis. #emph[Finite volume methods for unidirectional dispersive wave models]. #venue[Int. J. Num. Meth. Fluids], #strong[71], 717–736, 2013 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-00538043/")],
  yd("2012"),
  [F. Fedele and #me. #emph[Special solutions to a compact equation for deep-water gravity waves]. #venue[J. Fluid Mech.], #strong[712], 646–660, 2012 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-00687325/")],
  [#me, D. Mitsotakis, L. Chubarov and Yu. Shokin. #emph[On the contribution of the horizontal sea-bed displacements into the tsunami generation process]. #venue[Ocean Modelling], #strong[56], 43–56, 2012 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-00530999/")],
  [F. Fedele and #me. #emph[Solitary wave interaction in a compact equation for deep-water gravity waves]. #venue[JETP Letters], #strong[95]​(12), 703–706, 2012 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-00687668/")],
  [S.A. Beisel, L.B. Chubarov, #me, G.S. Khakimzyanov and N.Yu. Shokina. #emph[Simulation of surface waves generated by an underwater landslide in a bounded reservoir]. #venue[Russ. J. Numer. Anal. Math. Modelling], #strong[27]​(6), 539–558, 2012 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-00788284/")],
  [D. Clamond and #me. #emph[Practical use of variational principles for modeling water waves]. #venue[Physica D], #strong[241]​(1), 25–36, 2012 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-00456891/")],
  yd("2011"),
  [F. Fedele and #me. #emph[Hamiltonian form and solitary waves of the spatial Dysthe equations]. #venue[JETP Letters], #strong[94]​(12), 921–925, 2011 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-00633389/")],
  [#me, C. Labart and D. Mitsotakis. #emph[Long wave runup on random beaches]. #venue[Phys. Rev. Lett.], #strong[107], 184504, 2011 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-00606627/")],
  [T. Stefanakis, F. Dias and #me. #emph[Local Run-Up Amplification by Resonant Wave Interactions]. #venue[Phys. Rev. Lett.], #strong[107], 124502, 2011 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-00605461/")],
  [#me and D. Clamond. #emph[Shallow water equations for large bathymetry variations], #venue[J. Phys. A: Math. Theor.] #strong[44], 332001, 2011 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-00580310/")],
  [#me, C. Acary-Robert and D. Bresch. #emph[Mathematical modeling of powder-snow avalanche flows]. #venue[Studies in Applied Mathematics], #strong[127]​(1), 38–66, 2011 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-00354000/")],
  [#me, R. Poncet and F. Dias. #emph[The VOLNA code for the numerical modelling of tsunami waves: generation, propagation and inundation]. #venue[European Journal of Mechanics B/Fluids], #strong[30]​(6), 598–615, 2011 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-00454591/")],
  [#me, Th. Katsaounis and D. Mitsotakis. #emph[Finite volume schemes for dispersive wave propagation and runup]. #venue[J. Comp. Phys.], #strong[230], 3035–3061, 2011 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-00472431/")],
  yd("2010"),
  [Y. Meyapin, #me and M. Gisclon. #emph[Velocity and energy relaxation in two-phase flows]. #venue[Studies in Applied Mathematics], #strong[125(2)], 179 – 212, 2010 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-00440852/")],
  [#me and D. Mitsotakis. #emph[On the relevance of the dam break problem in the context of nonlinear shallow water equations]. #venue[Discrete and Continuous Dynamical Systems], #strong[13]​(4), 799–818, 2010 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-00369795/")],
  [#me and F. Dias. #emph[Influence of sedimentary layering on tsunami generation], #venue[Computer Methods in Applied Mechanics and Engineering], #strong[199], 1268–1275, 2010 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-00288696/")],
  [F. Dias, #me and J.-M. Ghidaglia. #emph[A two-fluid model for violent aerated flows], #venue[Computers and Fluids], 39(2), 283–293, 2010 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-00285037/")],
  yd("2009"),
  [#me. #emph[Group and phase velocities in the free-surface visco-potential flow: new kind of boundary layer induced instability]. #venue[Physics Letters A], #strong[373], 3212–3216, 2009 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-00334440/")],
  [#me. #emph[Visco-potential free-surface flows and long wave modelling]. #venue[European Journal of Mechanics B/Fluids], #strong[28]​(3), 430–443, 2009 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-00270926/")],
  [#me and F. Dias. #emph[Energy of tsunami waves generated by bottom motion]. #venue[Proc. R. Soc. A] (2009) #strong[465], 725–744 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-00311752/")],
  [#me and F. Dias. #emph[Tsunami generation by dynamic displacement of sea bed due to dip-slip faulting]. #venue[Math. Comp. Sim.], #strong[80]​(4), 837-848, 2009 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-00174439/")],
  yd("2007"),
  [#me and F. Dias. #emph[Viscous potential free-surface flows in a fluid layer of finite depth], #venue[C. R. Acad. Sci. Paris], Ser. I, #strong[345], 113–118, 2007 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-00145315/")],
  [#me and F. Dias. #emph[Dissipative Boussinesq equations], #venue[C. R. Mcanique], #strong[335], 559–583, 2007 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-00137633/")],
  [Y. Kervella, #me and F. Dias. #emph[Comparison between three-dimensional linear and nonlinear tsunami generation models], #venue[Theor. Comput. Fluid Dyn.], #strong[21]:245–269, 2007 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-00113909/")],
  yd("2006"),
  [#me, F. Dias and Y. Kervella. #emph[Linear theory of wave generation by a moving bottom], #venue[C. R. Acad. Sci. Paris], Ser. I #strong[343], 499–504, 2006 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-00114954/")],
))

=== Book chapters

#pub-list(category: "Book chapters", (
  yd("2025"),
  [R. Matar, N. Abcha, N. Lecoq, E.-I. Turki, I. Abroug and #me. #emph[Exploring Extreme Wave Propagation in Coastal Zones: A Combined Physical and Numerical Modeling Study], In A.-C. Bennis, J.-C. Dauvin, E. Feunteun, T. Komatsu, O. Matsuda and P. Prouzet (Eds.) Constraints and Adaptations to Global Change at the Land-Sea Interface: For a Shared Ecological and Energy Transition, Proceedings of the 19#up[th] French–Japanese Oceanography Symposium, COAST 2023, Springer, Cham, pp. 3–18, 2025],
  yd("2024"),
  [M. Zafar, #me, P. Sabatier, M. Banjan and J. Kim. #emph[Uncovering a Paleotsunami Triggered by Mass-Movement in an Alpine Lake]. In: P. Gourbesville, G. Caignaert (Eds.) Advances in Hydroinformatics — SimHydro 2023 Volume 2. SimHydro 2023. Springer Water. Springer, Singapore, pp. 47–64, 2024 #linebreak() #link("https://hal.science/hal-04261487/")],
  yd("2022"),
  [T.S.B. Abd Manan, T. Khan, W.H.M. Wan Mohtar, A. Machmudah, #me, S. Qazi, A. Ahmad and N. Wan Rasdi. #emph[Bioremediation of wastewater using algae for potential renewable bioenergy cogeneration], In A. Ahmad, F. Banat and H. Taher (Eds.) Algal Biotechnology: Integrated Algal Engineering for Bioenergy, Bioremediation, and Biomedical Applications, Elsevier, Amsterdam, pp. 47–62, 2022],
  yd("2021"),
  [V. Roubtsov and #me. #emph[Poisson and Symplectic structures, Hamiltonian action, momentum and reduction], In M. Ulan and E. Schneider (Eds.) Differential Geometry, Differential Equations, and Mathematical Physics. Birkhäuser, Cham, pp. 1–29, 2021 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-02522156/")],
  [S. Lespinats, B. Colange and #me. #emph[Data Science Context], In: Nonlinear Dimensionality Reduction Techniques: A Data Structure Preservation Approach, Springer, Cham, pp. 1–30, 2021 #linebreak() #link("https://doi.org/10.1007/978-3-030-81026-9_1")],
  [S. Lespinats, B. Colange and #me. #emph[Intrinsic Dimensionality], In: Nonlinear Dimensionality Reduction Techniques: A Data Structure Preservation Approach, Springer, Cham, pp. 31–44, 2021 #linebreak() #link("https://doi.org/10.1007/978-3-030-81026-9_2")],
  [S. Lespinats, B. Colange and #me. #emph[Map Evaluation], In: Nonlinear Dimensionality Reduction Techniques: A Data Structure Preservation Approach, Springer, Cham, pp. 45–66, 2021 #linebreak() #link("https://doi.org/10.1007/978-3-030-81026-9_3")],
  [S. Lespinats, B. Colange and #me. #emph[Map Interpretation], In: Nonlinear Dimensionality Reduction Techniques: A Data Structure Preservation Approach, Springer, Cham, pp. 67–88, 2021 #linebreak() #link("https://doi.org/10.1007/978-3-030-81026-9_4")],
  [S. Lespinats, B. Colange and #me. #emph[Stress Functions for Unsupervised Dimensionality Reduction], In: Nonlinear Dimensionality Reduction Techniques: A Data Structure Preservation Approach, Springer, Cham, pp. 89–118, 2021 #linebreak() #link("https://doi.org/10.1007/978-3-030-81026-9_5")],
  [S. Lespinats, B. Colange and #me. #emph[Stress Functions for Supervised Dimensionality Reduction], In: Nonlinear Dimensionality Reduction Techniques: A Data Structure Preservation Approach, Springer, Cham, pp. 119–156, 2021 #linebreak() #link("https://doi.org/10.1007/978-3-030-81026-9_6")],
  [S. Lespinats, B. Colange and #me. #emph[Optimization, Acceleration and Out of Sample Extensions], In: Nonlinear Dimensionality Reduction Techniques: A Data Structure Preservation Approach, Springer, Cham, pp. 157–176, 2021 #linebreak() #link("https://doi.org/10.1007/978-3-030-81026-9_7")],
  [S. Lespinats, B. Colange and #me. #emph[Applications of Dimensionality Reduction to the Diagnosis of Energy Systems], In: Nonlinear Dimensionality Reduction Techniques: A Data Structure Preservation Approach, Springer, Cham, pp. 177–192, 2021 #linebreak() #link("https://doi.org/10.1007/978-3-030-81026-9_8")],
  yd("2020"),
  [G. Khakimzyanov, #me, Z. Fedotova and O. Gusev. #emph[Model Derivation on a Globally Flat Space], In: Dispersive Shallow Water Waves: Theory, Modeling, and Numerical Methods, Lecture Notes in Geosystems Mathematics and Computing, Birkhäuser, Cham, pp. 1–43, 2020 #linebreak() #link("https://doi.org/10.1007/978-3-030-46267-3_1")],
  [G. Khakimzyanov, #me, Z. Fedotova and O. Gusev. #emph[Numerical Simulation on a Globally Flat Space], In: Dispersive Shallow Water Waves: Theory, Modeling, and Numerical Methods, Lecture Notes in Geosystems Mathematics and Computing, Birkhäuser, Cham, pp. 45–134, 2020 #linebreak() #link("https://doi.org/10.1007/978-3-030-46267-3_2")],
  [G. Khakimzyanov, #me, Z. Fedotova and O. Gusev. #emph[Model Derivation on a Globally Spherical Geometry], In: Dispersive Shallow Water Waves: Theory, Modeling, and Numerical Methods, Lecture Notes in Geosystems Mathematics and Computing, Birkhäuser, Cham, pp. 135–190, 2020 #linebreak() #link("https://doi.org/10.1007/978-3-030-46267-3_3")],
  [G. Khakimzyanov, #me, Z. Fedotova and O. Gusev. #emph[Numerical Simulation on a Globally Spherical Geometry], In: Dispersive Shallow Water Waves: Theory, Modeling, and Numerical Methods, Lecture Notes in Geosystems Mathematics and Computing, Birkhäuser, Cham, pp. 191–237, 2020 #linebreak() #link("https://doi.org/10.1007/978-3-030-46267-3_4")],
  yd("2019"),
  [T. Torsvik, A. Abdalazeez, #me, P. Denissenko and I. Didenkulova. #emph[Dispersive and non-dispersive nonlinear long wave transformations: numerical and experimental results], In A. #sc[Berezovski] and T. #sc[Soomere] (Eds.) Applied Wave Mathematics II, Mathematics of Planet Earth, Vol. #strong[6]. pp. 41–66, Springer Cham, 2019 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-02289778/")],
  [N. Mendes, M. Chhay, J. Berger and #me. #emph[A Brief History of Diffusion in Physics], In: Numerical Methods for Diffusion Phenomena in Building Physics, Springer, Cham, pp. 1–5, 2019 #linebreak() #link("https://doi.org/10.1007/978-3-030-31574-0_1")],
  [N. Mendes, M. Chhay, J. Berger and #me. #emph[Heat and Mass Diffusion in Porous Building Elements], In: Numerical Methods for Diffusion Phenomena in Building Physics, Springer, Cham, pp. 9–43, 2019 #linebreak() #link("https://doi.org/10.1007/978-3-030-31574-0_2")],
  [N. Mendes, M. Chhay, J. Berger and #me. #emph[Finite-Difference Method], In: Numerical Methods for Diffusion Phenomena in Building Physics, Springer, Cham, pp. 45–87, 2019 #linebreak() #link("https://doi.org/10.1007/978-3-030-31574-0_3")],
  [N. Mendes, M. Chhay, J. Berger and #me. #emph[Basics in Practical Finite-Element Method], In: Numerical Methods for Diffusion Phenomena in Building Physics, Springer, Cham, pp. 89–100, 2019 #linebreak() #link("https://doi.org/10.1007/978-3-030-31574-0_4")],
  [N. Mendes, M. Chhay, J. Berger and #me. #emph[Explicit Schemes with Improved CFL Condition], In: Numerical Methods for Diffusion Phenomena in Building Physics, Springer, Cham, pp. 103–120, 2019 #linebreak() #link("https://doi.org/10.1007/978-3-030-31574-0_5")],
  [N. Mendes, M. Chhay, J. Berger and #me. #emph[Reduced Order Methods], In: Numerical Methods for Diffusion Phenomena in Building Physics, Springer, Cham, pp. 121–152, 2019 #linebreak() #link("https://doi.org/10.1007/978-3-030-31574-0_6")],
  [N. Mendes, M. Chhay, J. Berger and #me. #emph[Boundary Integral Approaches], In: Numerical Methods for Diffusion Phenomena in Building Physics, Springer, Cham, pp. 153–166, 2019 #linebreak() #link("https://doi.org/10.1007/978-3-030-31574-0_7")],
  [N. Mendes, M. Chhay, J. Berger and #me. #emph[Spectral Methods], In: Numerical Methods for Diffusion Phenomena in Building Physics, Springer, Cham, pp. 167–209, 2019 #linebreak() #link("https://doi.org/10.1007/978-3-030-31574-0_8")],
  [N. Mendes, M. Chhay, J. Berger and #me. #emph[Exercises and Problems], In: Numerical Methods for Diffusion Phenomena in Building Physics, Springer, Cham, pp. 213–227, 2019 #linebreak() #link("https://doi.org/10.1007/978-3-030-31574-0_9")],
  [N. Mendes, M. Chhay, J. Berger and #me. #emph[Conclusions], In: Numerical Methods for Diffusion Phenomena in Building Physics, Springer, Cham, pp. 229–232, 2019 #linebreak() #link("https://doi.org/10.1007/978-3-030-31574-0_10")],
  yd("2018"),
  [A. Durán, #me and D. Mitsotakis. #emph[Peregrine’s system revisited], In N. #sc[Abcha], E. #sc[Pelinovsky] and I. #sc[Mutabazi] (Eds.) Nonlinear Waves and Pattern Dynamics, pp. 3–43, Springer Cham, 2018 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-01703491/")],
  yd("2016"),
  [D. Clamond and #me. #emph[Modeling water waves beyond perturbations], in E. #sc[Tobisch] (Ed.): New Approaches to Nonlinear Waves, Lecture Notes in Physics (#strong[908]), 197–210, Springer, 2016 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-01102120/")],
  yd("2014"),
  [D. Clamond and #me. #emph[A Non-Hydrostatic Non-Dispersive Shallow Water Model], Ph. #sc[Goubersville] #emph[et al.] (Eds.): Springer Hydrogeology. Advances in Hydroinformatics: SIMHYDRO 2012 — New Frontiers of Simulation, 197–206, Springer Singapore 2014 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-00907110/")],
  [V. Guinot, D. Clamond and #me. #emph[Finite Volume Implementation of Non-Dispersive, Non-Hydrostatic Shallow Water Equations], Ph. #sc[Goubersville] #emph[et al.] (Eds.): Springer Hydrogeology. Advances in Hydroinformatics: SIMHYDRO 2012 — New Frontiers of Simulation, 189–196, Springer Singapore 2014 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-00907108/")],
  yd("2011"),
  [Y. Meyapin, #me and M. Gisclon. #emph[Two-fluid barotropic models for powder-snow avalanche flows], E. Krause #emph[et al.] (Eds.): Computational Sci. & High Performance Computing IV, NNFM 115, pp. 219–232. Springer-Verlag Berlin Heidelberg 2011 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-00394437/")],
  yd("2007"),
  [#me and F. Dias, #emph[Water waves generated by a moving bottom]. In book: “Tsunami and Nonlinear Waves”, A. #sc[Kundu] (Editor), pp. 65–95, Springer Verlag 2007, Approx. 325 p., 170 illus., Hardcover, ISBN: 978-3-540-71255-8 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-00115875/")],
  yd("2006"),
  [F. Dias and #me. #emph[Dynamics of tsunami waves]. In Book: “Extreme Man-Made and Natural Hazards in Dynamics of Structures”, A. #sc[Ibrahimbegovic] and I. #sc[Kozar] (Eds), Springer Dordrecht, NATO Advanced Research Workshop, Opatija, Croatia, May 28 — June 1, pp. 35–60, 2006 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-00113612/")],
))

=== Peer-reviewed conference proceedings

#pub-list(category: "Peer-reviewed conference proceedings", (
  yd("2022"),
  [S. Mustatea, M. Aupetit, J. Peltonen, S. Lespinats, #me. #emph[Supervised dimensionality reduction technique accounting for soft classes], European Symposium on Artificial Neural Networks, Computational Intelligence and Machine Learning (ESANN), Bruges, Belgium, 5–7 October 2022 #linebreak() #link("https://www.esann.org/sites/default/files/proceedings/2022/ES2022-26.pdf")],
  yd("2020"),
  [B. Colange, J. Peltonen, M. Aupetit, #me and S. Lespinats. #emph[Steering Distortions to Preserve Classes and Neighbors in Supervised Dimensionality Reduction], 34#up[th] Conference on Neural Information Processing Systems (NeurIPS 2020), Vancouver, Canada, 2020 #linebreak() #text(size: 0.9em)[ #link("https://proceedings.neurips.cc/paper/2020/hash/99607461cdb9c26e2bd5f31b12dcf27a-Abstract.html")]],
  [M. Loukili, K. Kotrasova and D. #strong[Dutykh]. #emph[A computational simulation of steady natural convection in an $H-$form cavity]. In Silhavy R., Silhavy P., Prokopova Z. (Eds.) Software Engineering Perspectives in Intelligent Systems. CoMeSySo 2020. Advances in Intelligent Systems and Computing, Vol. #strong[1295], pp. 164-177, Springer International Publishing, Cham, 2020 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-02615655/")],
  [A. Abdalazeez, I. Didenkulova and #me. #emph[Dispersive effects during long wave run-up on a plane beach] in “Advances in Natural Hazards and Hydrological Risks: Meeting the Challenge”, Proceedings of the 2#up[nd] International Workshop on Natural Hazards (NatHaz’19), Pico Island – the Azores 2019, F. Fernandes, A. Malheiro, H.I. Chaminé (Eds.), pp. 143–146, Springer International Publishing, Cham, 2020 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-02366937/")],
  yd("2019"),
  [B. Colange, L. Vuillon, S. Lespinats and #me. #emph[Interpreting Distortions in Dimensionality Reduction by Superimposing Neighbourhood Graphs]. 2019 IEEE Visualization Conference (VIS), 20 – 25 October, Vancouver, BC, Canada, 2019 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-02290875/")],
  [M. Abdykarim, J. Berger, #me and A. Agbossou. #emph[An efficient numerical method for a long term simulation of heat and mass transfer: the case of an insulated rammed earth wall]. V. Corrado, E. Fabrizio, A. Gasparella and F. Patuzzi (Eds.), Proceedings of the 16#up[th] IBPSA Conference, pp. 1444 – 1451, Rome, Italy, September 2 – 4, 2019, ISBN: 978-1-7750520-1-2 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-02288858/")],
  [H. Geoffroy, J. Berger, B. Colange, S. Lespinats, #me, C. Buhé and G. Sauce. #emph[Use of Multidimensional Scaling for Fault Detection or Monitoring Support in A Continuous Commissioning]. V. Corrado, E. Fabrizio, A. Gasparella and F. Patuzzi (Eds.), Proceedings of the 16#up[th] IBPSA Conference, pp. 877 – 884, Rome, Italy, September 2 – 4, 2019, ISBN: 978-1-7750520-1-2 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-02411240/")],
  yd("2012"),
  [T. Stefanakis, F. Dias and #me. #emph[Resonant long-wave run-up on a plane beach]. ISOPE-2012 Rhodes Conference Proceedings, 2012 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-00728747/")],
  [L. O’Brien, P. Christodoulides, E. Renzi, #me and F. Dias. #emph[The force of a tsunami on a wave energy converter]. ISOPE-2012 Rhodes Conference Proceedings, 2012 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-00728888/")],
  yd("2011"),
  [#me, D. Mitsotakis, S. Beisel and N. Shokina. #emph[Dispersive waves generated by an underwater landslide]. Numerical methods for Hyperbolic Equations. Eds: Vazquez-Cendon #emph[et al.], Taylor & Francis Group, London, pp. 245–250, 2013. Proceedings of the Numerical Methods for Hyperbolic Equations: Theory and Applications. International Conference to honour Professor E.F. Toro in the month of his 65th birthday. Santiago de Compostela, Spain, July 4 – 8, 2011 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-00637102/")],
  [#me, Th. Katsaounis and D. Mitsotakis. #emph[Dispersive wave runup on non-uniform shores]. In: Fort J., Fürst J., Halama J., Herbin R., Hubert F. (Eds.) Finite Volumes For Complex Applications VI — Problems & Perspectives. Springer Proceedings in Mathematics, 2011, Volume #strong[4], Part 1, pp. 389–397 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-00553762/")],
  yd("2009"),
  [#me and F. Dias. #emph[How does sedimentary layering affect the generation of tsunamis?] Proceedings of OMAE 2009, 28th International Conference on Ocean, Offshore and Arctic Engineering, May 31 – June 5, 2009, Honolulu, USA],
  yd("2008"),
  [#me. #emph[Visco potential free-surface flows], XXII ICTAM, 25 – 29 August 2008, Adelaide, Australia],
  [F. Dias, #me and J.-M. Ghidaglia. #emph[Simulation of Free Surface Compressible Flows Via a Two Fluid Model], OMAE 2008, Nick #sc[Newman]’s Symposium on Marine Hydrodynamics, #strong[6], 43–50, 2008. Estoril, Portugal, 15 – 20 June 2008 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-00258161/")],
))

=== Conference proceedings

#pub-list(category: "Conference proceedings", (
  yd("2025"),
  [S. Mukherjee, L. Vuillon, L. Bou-Nassif, S. Giroux-Julien, H. Pabiou, #me and I. Tsanakas. #emph[Temporal Graph Neural Networks for Early Anomaly Detection and Performance Prediction via PV System Monitoring Data] in Proc. 42nd European Photovoltaic Solar Energy Conference and Exhibition (EU PVSEC 2025), Bilbao, Spain, 020338, pp. 001–003, 2025 #linebreak() #link("https://arxiv.org/abs/2512.03114/")],
  [M. Zafar, P. Sabatier, #me, H. Jomard, W. Rapuc, P. Lajeunesse and E. Chapron. #emph[Modeling earthquake-induced seiche process and subsequent homogenite deposits in lacustrine setting], EGU General Assembly 2025, Vienna, Austria, 27 Apr – 2 May 2025, EGU25-2461, 2025 #linebreak() #link("https://doi.org/10.5194/egusphere-egu25-2461/")],
  yd("2024"),
  [A. Rashidi, #me, Ch. Beck and M. Najaftomaraei. #emph[Unraveling Tsunami Hazards along the Lesser Antilles, Eastern Caribbean Plate], Proceedings of the 21st Iranian Geophysical Conference, December 10-11, Tehran, Iran, pp. 1318–1323, 2024],
  [S. Mukherjee, L. Vuillon, #me and I. Tsanakas. #emph[Dimensionality Reduction of Environmental Data for Long-Term PV Performance Analysis Using Graph Based Methods], EU PVSEC 2024, #strong[020411], pp. 001–004, 2024 #linebreak() #link("https://userarea.eupvsec.org/proceedings/EU-PVSEC-2024/4CV.1.27/")],
  [C. Cárdenas-Bravo, S. Lespinats and #me. #emph[A Practical Example of the Impact of Uncertainty on the One-Dimensional Single-Diode Model], 2024 IEEE International Symposium on Systems Engineering (ISSE), Perugia, Italy, pp. 1–5, 2024 #linebreak() #link("https://ieeexplore.ieee.org/document/10741111/")],
  [M. Zafar, #me, P. Sabatier, M. Banjan and J. Kim. #emph[Uncovering a Paleotsunami Triggered by Mass-Movement in an Alpine Lake]. In: P. Gourbesville, G. Caignaert (Eds.) Advances in Hydroinformatics — SimHydro 2023 Volume 2. SimHydro 2023. Springer Water. Springer, Singapore, pp. 47–64, 2024 #linebreak() #link("https://hal.science/hal-04261487/")],
  [A. Rashidi, M. Mokhtari, #me, M. Masoodi, P. Faridi and S. Kiani. #emph[A glimpse into tsunami hazard research in Makran with a focus on complex tsunamis]. The 9#up[th] International Conference on Seismology and Earthquake Engineering, Tehran, Iran, 2024],
  [F. Carbone and #me. #emph[Route to chaos and resonant triads interaction in a truncated Rotating Nonlinear shallow-water model], EGU General Assembly 2024, Vienna, Austria, 14–19 Apr 2024, EGU24–13180, 2024 #linebreak() #link("https://doi.org/10.5194/egusphere-egu24-13180/")],
  yd("2023"),
  [M. Bowen, P. Samozino, M. Vonderscher, #me and B. Morel. #emph[Development of a force-endurance model able to describe the muscle fatigability in the severe domain and validation of the RACLET test], 28#up[th] annual congress of the European College of Sport Science, Paris, France, 4–7 July 2023 #linebreak() #link("https://hal.science/hal-04084767/")],
  yd("2022"),
  [C. Cardenas-Bravo, #me and D.L. Ha. #emph[Computation of Faulty IV Curves Based on a Distributed Solar Cell Algorithm], 8#up[th] World Conference on Photovoltaic Energy Conversion, Milano, Italy, 26–30 September 2022, pp. 701–703 #linebreak() #link("https://www.eupvsec-proceedings.com/proceedings?char=C&paper=50890")],
  [M. Cugnet, F. Gallois, A. Kirchev and #me. #emph[Understanding self-discharge or what’s going on inside a lead-acid battery when nothing happens outside], AABC Europe — 12#up[th] International Advanced Automotive Battery Conference, 13 – 15 June 2022, Mainz, Germany #linebreak() #link("https://hal.insa-toulouse.fr/LITEN/cea-03715092/")],
  [I. Didenkulova, A. Abdalazeez, #me and P. Denissenko. #emph[Effects of coastal roughness on long wave runup], EGU General Assembly 2022, Vienna, Austria, 23 – 27 May 2022, EGU22-8520 #linebreak() #link("https://doi.org/10.5194/egusphere-egu22-8520/")],
  yd("2020"),
  [A. Rashidi, #me, Z.H. Shomali and N.K. Farajkhah. #emph[Probabilistic Tsunami Hazard of Splay and Normal Faults in the Western Makran/Iran], The Second Eurasian RISK-2020 Conference and Symposium, Tbilisi, Georgia #linebreak() #link("https://www.researchgate.net/publication/343336669_Probabilistic_Tsunami_Hazard_of_Splay_and_Normal_Faults_in_the_Western_MakranIran/")],
  [S. Rusconi, #me, A. Zarnescu, D. Sokolovski and E. Akhmatskaya. #emph[Population balance approach for predicting polymer particles morphology]. The 11#up[th] Conference on Dynamical Systems Applied to Biology and Natural Sciences (DSABNS), Trento, Italy, 4 – 7 February 2020. ISBN: 978-989-98750-7-4 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-02518323/")],
  yd("2019"),
  [A. Abdalazeez, I. Didenkulova and #me. #emph[Nonlinear deformation and run-up of tsunami waves of positive polarity: numerical simulations and analytical predictions]. The First Eurasian conference “Risk – 2019”, Baku, Azerbaijan; 22 – 24 May 2019 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-02145105/")],
  yd("2017"),
  [I. Didenkulova, D. Senichev and #me. #emph[Statistics for long irregular wave run-up on a plane beach from direct numerical simulations]. European Geosciences Union, Vienna, Austria; 23 – 28 April 2017. Geophysical Research Abstracts, #strong[19], p. 19133 #linebreak() #link("https://meetingorganizer.copernicus.org/EGU2017/EGU2017-19133.pdf")],
  [D. Senichev, I. Didenkulova and #me. #emph[Study of statistics of random wave runup on a beach using direct numerical simulations]. Proceedings of the 23#up[rd] International scientific conference “Information Systems and Technologies” (IST–2017), 21#up[st] April 2017, Nizhny Novgorod, Russia; pp. 1001–1006 (in Russian)],
  [M. Gisclon, M. Chhay, #me and C. Ruyer-Quil. #emph[Modélisation mathématique des films minces avec applications aux transferts de chaleur]. Congrès Français de Mécanique, Lille, France; 28 August – 1 September 2017. Publisher: Association Française de Mécanique (AFM) #linebreak() #link("https://cfm2017.sciencesconf.org/135353/template_cfm2017_vf.pdf")],
  yd("2016"),
  [I. Didenkulova, #me and D. Senichev. #emph[Statistics for long wave run-up on a slopping beach: theoretical predictions and experimental data]. 15#up[th] Plinius Conference on Mediterranean Risks, Giardini Naxos, Italy; 8–11 June 2016. Publisher: Plinius Conference Abstracts, #strong[15], p. 38.],
  yd("2015"),
  [M. Chhay, #me, M. Gisclon and C. Ruyer-Quil. #emph[Modélisation mathématiques des films minces]. Congrès Français de Mécanique, Lyon, France; 24 – 28 August 2015. Publisher: Association Française de Mécanique (AFM) #linebreak()],
  [D. Clamond, #me and A. Galligo. #emph[Computer Algebra Applied to a Solitary Waves Study]. In Proceedings of the 2015 ACM on International Symposium on Symbolic and Algebraic Computation – ISSAC’15, ACM Press, 125–132, 2015],
  yd("2014"),
  [A. Galligo, #me and D. Clamond. #emph[On detection of solitary waves, using phase diagrams and real discriminant]. In J.E. Garcia, J. Fernández Sánchez and M. Sombra (Eds.), Proceedings of the Encuentros de Algebra Computacional y aplicaciones Conference, Barcelona, Spain, 18 – 20 June 2014, pp. 119–122],
  [#me and J.-G. Caputo. #emph[Sine-Gordon dynamics on graphs]. In O.O. Kochubey #emph[et al]. (Eds.), Applied problems of the fluid mechanics and heat and mass transfer (pp. 29–31). Dnipropetrovsk, Ukraine. Dnipropetrovsk National University. pp 192, 2014],
  [#me and D. Clamond. #emph[Modified Shallow Water Equations for Mild-slope Seabeds]. IWWWFB29, 30 March – 2 April 2014, Osaka, Japan, IWWWFB, 2014],
  [F. Carbone, #me, J.M. Dudley and F. Dias. #emph[Extreme wave run-up on a vertical cliff]. In Zbornik radova konferencije MIT 2013, pp. 99–103, Beograd, Serbia, 2014],
  yd("2013"),
  [F. Carbone, #me, J.M. Dudley and F. Dias. #emph[Extreme wave run-up on a vertical cliff]. IWWWFB28, 7 – 10 April 2013, Marseille, France #linebreak() #link("https://hal.archives-ouvertes.fr/hal-00927313/")],
  yd("2012"),
  [#me, D. Mitsotakis, S. Beisel and N. Shokina. #emph[On waves generated by an underwater landslide]. In Proceedings of the IV Conference “Applied Problems of the fluid mechanics, heat and mass transfer”, 1 – 3 November 2012, Dnepropetrovsk, Ukraine, pp. 75–79, 2012],
  yd("2010"),
  [#me, Th. Katsaounis and D. Mitsotakis. #emph[Finite volume schemes for Boussinesq type equations]. Proceedings of Colloque EDP-Normandie, 28 – 29 October 2010, Caen, France, pp. 15–21 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-00553754/")],
  [D. Clamond and #me. #emph[Dispersive wave equation derivation from a relaxed variational formulation]. Applied problems of aerodynamics, heat and mass transfers, pp. 40–42, Dnepropetrovsk, Ukraine, November 4 – 6, 2010],
  yd("2008"),
  [#me and F. Dias. #emph[Tsunami wave energy], 4th Canadian Conference on Geohazards, Universit Laval, May 20 – 24, 7 p., 2008 #linebreak() #link("https://hal.science/hal-04474849/")],
  yd("2007"),
  [#me and F. Dias, #emph[Fault dynamics and tsunami generation], ECCOMAS Thematic Conference on Multi-scale Computational Methods for Solids and Fluids. A. Ibrahimbegovic, F. Dias, H. Matthies, P. Wriggers (eds.), 79–81, 2007],
  [C. Kassiotis, F. Dias, A. Ibrahimbegovic and #me, #emph[A partitioned approach to model tsunami impact on coastal protections], ECCOMAS Thematic Conference on Multi-scale Computational Methods for Solids and Fluids. A. Ibrahimbegovic, F. Dias, H. Matthies, P. Wriggers (eds.), 134–139, 2007],
))

=== Research reports

#pub-list(category: "Research reports", (
  yd("2020"),
  [J. Berger, T. Busser, #me and N. Mendes. Retraction notice to “#emph[On the estimation of moisture permeability and advection coefficients of a wood fibre material using the optimal experiment design approach]” \[Exp. Therm. Fluid Sci. 90 (2017) 246–259\], Exp. Therm. Fluid Sci., #strong[113], 109808, 2020],
  yd("2016"),
  [#me. #emph[How to overcome the Courant-Friedrichs-Lewy condition of explicit discretizations?]. Technical report, 20 pp, 2016 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-01401125/")],
  yd("2015"),
  [#me and L. Gosse. #emph[Some topics of the NumHyp–2015’ discussion session]. 25 pp., 2015 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-02485301/")],
  yd("2014"),
  [Ch. Lalanne, A. Rafiee, #me, M. Lysaght and F. Dias. #emph[Enabling the UCD–SPH code on the Xeon Phi], 12 pp., 2014 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-00927227/")],
  yd("2011"),
  [F. Fedele and #me. #emph[Hamiltonian description and traveling waves of the spatial Dysthe equations], 2011 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-00632862/")],
  yd("2009"),
  [F. Dias, #me and J.-M. Ghidaglia. #emph[A compressible two-fluid model for the finite volume simulation of violent aerated flows. Analytical properties and numerical results], 2009 #linebreak() #link("http://hal.archives-ouvertes.fr/hal-00279671/")],
  yd("2008"),
  [#me. #emph[Visco-potential free-surface flows]. Research report of CMLA, 2008],
))

=== Book reviews

#pub-list(category: "Book reviews", (
  [M. S. Howe, #emph[Hydrodynamics and Sound], Cambridge University Press, Cambridge (2007). European Journal of Mechanics - B/Fluids, #strong[27(2)], 218, 2008 #linebreak() #link("https://hal.science/hal-04474814/")],
))

=== Theses

#pub-list(category: "Theses", (
  [#me. #emph[Mathematical modeling in the environment], Habilitation à diriger des recherches, University of Savoie, 2010 #linebreak() #link("http://tel.archives-ouvertes.fr/tel-00542937/")],
  [#me. #emph[Mathematical modeling of tsunami waves], PhD thesis, CMLA, ENS de Cachan, 2007 #linebreak() #link("http://tel.archives-ouvertes.fr/tel-00194763/")],
  [#me. #emph[Moving load on a layered floating ice sheet], Master 2 MN2MC thesis, CMLA, ENS de Cachan, 2005 #linebreak() #link("https://arxiv.org/abs/2402.16890/")],
  [#me. #emph[Harmonic oscillations of an inhomogeneous elastic layer under the action of a stamp] (in Ukrainian), Master thesis, Faculty of Applied Mathematics, Oles Honchar National University, Dnepropetrovsk, Ukraine, 2004],
  [#me. #emph[Harmonic oscillations of an inhomogeneous elastic layer] (in Ukrainian), Bachelor thesis, Faculty of Applied Mathematics, Oles Honchar National University, Dnepropetrovsk, Ukraine, 2003],
))

=== Various writings

#pub-list(category: "Various writings", (
  [#me. #emph[How to overcome the Courant-Friedrichs-Lewy condition of explicit discretizations?]. Technical report, 20 pp, 2016 #linebreak() #link("https://hal.archives-ouvertes.fr/hal-01401125/")],
  [#me. #emph[A brief introduction to pseudo-spectral methods: application to diffusion problems]. Lecture notes, 38 pp, 2016 #linebreak() #link("https://cel.archives-ouvertes.fr/cel-01256472/")],
  [#me. #emph[Introduction into Hydrodynamics. Variational point of view]. Lecture notes (work in progress), 142 pp, 2015 #linebreak() #link("https://github.com/dutykh/hydro/")],
  [#me. #emph[My favourite books, papers and software libraries]. Informal notes (work in progress), 18 pp, 2015 #linebreak() #link("https://github.com/dutykh/libs/")],
  [#me. #emph[Mathematical exercises (with solutions)]. Work in progress, 40 pp, 2015 #linebreak() #link("https://github.com/dutykh/exos/")],
))

=== General audience articles

#pub-list(category: "General audience articles", (
  [#link("https://www.univ-smb.fr/2020/12/09/classnerv-une-nouvelle-methode-extremement-efficace-pour-lanalyse-de-donnees/")[ClassNeRV, une nouvelle méthode extrêmement efficace pour l’analyse de données], Le Fil d’Actualité de l’Université Savoie Mont Blanc, December 9, 2020],
  [#link("http://www.scrivial.com/articles/a-dive-into-tsunami-the-terrifying-energy-it-possesses")[A dive into tsunami — the terrifying energy it possesses!] #link("http://www.scrivial.com/")[Scrivial.com], 2015],
  [C. Acary-Robert, D. Bresch and #me. #emph[Simulation d’avalanches de neige]. Actualités scientifiques de l’INSMI (CNRS), 14 mars 2012 #linebreak() #link("http://www.cnrs.fr/insmi/spip.php?article441")],
  [C. Acary-Robert, #me and M. Gisclon. #emph[Un modello per simulare numericamente le valanghe di neve]. Translation by Roberto Natalini, 2011 #linebreak() #text(size: 0.9em)[#link("maddmaths.simai.eu/focus/un-modello-per-simulare-numericamente-le-valanghe-di-neve/")]],
  [C. Acary-Robert, #me and M. Gisclon. #emph[Une approche pour simuler des avalanches de neige]. #link("http://images.math.cnrs.fr/")[Images des mathématiques], 28 décembre 2011 #linebreak() #link("http://images.math.cnrs.fr/Une-approche-pour-simuler-des.html")],
  [#link("https://www.lemonde.fr/planete/article/2011/09/29/tsunamis-gare-aux-avalanches-et-a-la-deuxieme-vague_1580151_3244.html")[#emph[Tsunamis: gare aux “avalanches” et à la deuxième vague]]. Le Monde, 1#up[er] Octobre 2011],
  [#emph[New research may explain high runup from tsunami waves]. #link("http://physicsbuzz.physicscentral.com/2011/09/new-research-may-explain-high-runup.html")[PhysicsCentral], Blog of the American Physical Society. September, 19, 2011],
  [#emph[Tsunami Puzzle Explained]. Physical Review Focus, 16 September 2011 #linebreak() #link("http://focus.aps.org/story/v28/st11")],
  [#emph[Tuned into Earth]. CNRS International Magazine, #strong[21], April 2011],
  [#emph[Quelle est la différence entre un tsunami et un raz-de-marée?], Slate.fr, 24 mars 2011 #linebreak() #link("http://www.slate.fr/story/36093/difference-tsunami-raz-de-maree")],
  [#emph[Les maths à l’écoute de la Terre]. Le Journal du CNRS, #No 245, juin 2010],
  [#emph[Simuler une avalanche]. #link("http://www.larecherche.fr/")[La Recherche] N428 – Avril 2009],
  [#emph[Springy sediments may amplify tsunamis]. Issue 2662 of #link("http://www.newscientist.com/")[New Scientist magazine], 25 June 2008, page 20],
  [#emph[Comment naît un tsunami?], Le Mensuel de l’Université, #No 23, Février 2008],
))

